moveRegistry dont setOwner, signal moved if owner changed.
status-im/ens-usernames pull request #102
Opened 2020-02-07 19:04 UTC by 3esmit

Fixes #100
Alternative to #101 

Changes only how Moved state is defined. When `BaseRegistrarImplementation.reclaim(uint256,address)` is used, anyone can call the moveRegistry function to allow reclaim.

2020-07-09 05:35 UTC, rajeevgopalakrishna commented on contracts/registry/UsernameRegistrar.sol
> -        onlyController
Why is this modifier `onlyController` being removed here? Because this does not `setOwner` anymore?

2020-09-22 00:34 UTC, 3esmit commented on contracts/registry/UsernameRegistrar.sol
> -        onlyController
Yes, exactly

2020-09-25 09:52 UTC, rajeevgopalakrishna requested changes

2020-09-25 09:52 UTC, rajeevgopalakrishna commented on contracts/registry/UsernameRegistrar.sol
> +        require(state == RegistrarState.Active, "Wrong state");
Duplicates the `require` from two lines above.

2020-09-25 13:06 UTC, closed without merging