separate NFT logic
status-im/ens-usernames pull request #122
Opened 2020-11-09 15:58 UTC by 3esmit

Fixes #108

2020-11-13 06:35 UTC, rajeevgopalakrishna requested changes
Looks good. Requesting few minor changes/clarifications. It will help to walk over the refactored changes.

2020-11-13 06:35 UTC, rajeevgopalakrishna commented on contracts/registry/UsernameRegistrar.sol
> -        delete accounts[_label];
Don't we need to delete the account from this registry? Seems like we did earlier but this PR removes it.

2020-11-13 06:35 UTC, rajeevgopalakrishna commented on contracts/registry/UsernameToken.sol
> +    function generateToken(address _owner, bytes32 _label, uint256 _value, uint256 _creationTime) internal onlyController {
Suggest moving `onlyController` modifier to the `external` callers instead of the `internal` method.

2020-11-13 06:35 UTC, rajeevgopalakrishna commented on contracts/registry/UsernameToken.sol
> +    function destroyToken(bytes32 _label) internal onlyController {
Suggest moving `onlyController` modifier to the `external` callers instead of the `internal` method.

2020-11-13 06:35 UTC, rajeevgopalakrishna commented on contracts/registry/UsernameRegistrar.sol
> +        accounts.deleteUser(_label);
Why wasn't this being done earlier?

2020-11-27 12:16 UTC, merged

2020-11-27 12:17 UTC, 0kok0 commented
good to go into develop from my side